### PR TITLE
Add hoglin spawner

### PR DESCRIPTION
**Pull request by PleaseInsertNameHere**
This pull request adds hoglin spawning in the nether

### CODE REVIEW

**Comment by PetteriM1** [comment]
You need to add it to max spawns and the config

**Comment by PleaseInsertNameHere** [comment]
Alright, done!

**Comment by PetteriM1** [comment]
You also need to make "spawning allowed by dimension" to allow them in nether and not in other dimensions

**Comment by PleaseInsertNameHere** [comment]
Added it

**Comment by PleaseInsertNameHere** [comment]
Are you still there?

**Pull request merged**
