### PR TITLE
Add max mob spawn count

### PR DESCRIPTION
**Pull request by Htepple**

### CODE REVIEW

**Comment by PetteriM1** [comment]
This was removed for a reason. You can use spawn ticks to set how much mobs spawn.

**Comment by Htepple** [comment]
If you use spawn ticks, then only 1 mob of each type will be spawned for each player. (sorry for my English)

**Comment by PetteriM1** [comment]
> If you use spawn ticks, then only 1 mob of each type will be spawned for each player. (sorry for my English)

No, it's per chunk.

**Comment by PetteriM1** [comment]
You are actually correct. I reverted the old code in the latest commit (34ddd6accf2ab80c14f0598237364eb49b611fc5).

**Comment by Htepple** [comment]
Thank you :3

**Pull request closed without merging**
