### PR TITLE
fix #112

### LINKED ISSUE #112: Endman not neutral
### Info
This is:
- [X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
Endman attack players when seeing players, it means that endman is not neutral

Config:
Default Config with only this plugin

### PR DESCRIPTION
**Pull request by zzz1999**

### CODE REVIEW

**Comment by PetteriM1** [comment]
This is still not the full vanilla behavior because they should become angry if player is looking at them. Anyways this is better than the current one but could you fix the code formatting?

**Comment by zzz1999** [comment]
ok
I know you mean.
I will try commit implement look enderman behavior tomorrow

**Comment by zzz1999** [comment]
look look look

**Comment by PetteriM1** [comment]
The code formatting is still wrong

**Comment by zzz1999** [comment]
uh
i dont know you mean actually
what format should I obe

**Comment by PetteriM1** [comment]
Now this does revert the latest commits...

**Comment by PetteriM1** [comment]
And use Ctrl+Alt+L or the "Reformat Code" button

**Comment by zzz1999** [comment]
I thought wrong,I inaccurate deem sth code struct regulations I havn't observe.My bad

**Comment by zzz1999** [comment]
Can merge?

**Comment by zzz1999** [comment]
i click wrong
really

**Comment by PetteriM1** [comment]
Are you sure that the data flag ID in makeVibrating() is correct?

**Comment by zzz1999** [comment]
i dont sure.i find all possible id but now a available,this is the last id i tried.need i remove that line?

**Comment by PetteriM1** [comment]
Did you test that this works?

**Comment by zzz1999** [comment]
doesn't work

**Comment by PetteriM1** [comment]
> doesn't work

This pr or the data flag?

**Comment by zzz1999** [comment]
I mean is this data flag is doesn't work but pr is work except data flag

**Comment by PetteriM1** [comment]
Ok I guess we can go with this for now

**Comment by zzz1999** [comment]
one day i will find the current flag and fix this,never mind this little inapposite

**Pull request merged**
